### PR TITLE
Try to clarify instructions

### PR DESCRIPTION
**Pull request by mrexodia**
For me it was quite difficult to follow the instructions, especially without having used Project64 in the past. I updated the instructions to (hopefully) clarify some things so it's easier to new people to enjoy this rom.

### CODE REVIEW

**Comment by LuigiBlood** [comment]
I won't really merge that as I really want to have instructions that works for every version, including Japanese, Development, everything.

**Comment by mrexodia** [comment]
Alright, I will do some updates to make it more generic for the disk expansion then. Could you be a bit more specific about which parts need to be more generic?

While I do think it’s good to strive for generic instructions, I also think it’s good to sometimes have a concrete example that people can follow. I read about this rom on n64today and wanted to try it out, but it took me much longer than I wanted, which is why I wanted to update the instructions.

**Comment by LuigiBlood** [comment]
The step by step patching instructions could be more generic to be honest.

**Comment by LuigiBlood** [comment]
Also I want to deal with the case where user has a ROM that's not big endian since No-Intro was very stupid about this stuff at one point...

**Comment by mrexodia** [comment]
I have updated the disk instructions to better line up with the original wording (eg no mention of 'American') and also removed the download link.

With regards to the step by step instructions being generic, I think the paragraph above describes things generically enough. I updated the title to clarify this is an example. The audience for this step-by-step instruction (in my mind) is enthusiasts who just want to play the mod. If you want I can create specific instructions for each ROM version, because being generic in an example only hurts the instructional value.

**Comment by LuigiBlood** [comment]
I'm fine with this, but I really want a case where the patch doesn't work because of the ROM endianness which is no one's fault and because ROM sites suck sometimes.

**Comment by mrexodia** [comment]
I just tried to apply the wrong patch to my rom and I got this:

fail

Does that cover your concerns?

**Comment by LuigiBlood** [comment]
Nope people just won't know what to do when the endianness is wrong even then it's a legit OoT ROM that's identical in content. That's why I mentioned Tool64.

**Comment by mrexodia** [comment]
I updated the instructions to try and cover this scenario in more depth.

**Comment by LuigiBlood** [comment]
This seems fine. I guess I'll merge this.

**Comment by mrexodia** [comment]
Great, thanks for your work on the game!

**Pull request merged**
